/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ccfb9a62-dd21-4a17-96b4-1fb034408021",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lO92kmYCm",
    "aws_user_pools_web_client_id": "idrriqo5dim41kue0mjc3hpju",
    "oauth": {},
    "aws_user_files_s3_bucket": "productpics185552-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
