require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'qury' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  # use_native_modules!
  # pod 'RNFileSelector', :path => '../node_modules/react-native-file-selector/ios'
  # use_frameworks!
  # pod 'FileBrowser', :git => 'https://github.com/prscX/FileBrowser'

   # Enables Flipper.
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable these next few lines.
   #use_flipper!({ 'Flipper-Folly' => '2.5.3' })
   use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
   
   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

   pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

   post_install do |installer|
    flipper_post_install(installer)
   end
end

